name: Build Android App

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Create Local Properties File
        run: cat /home/runner/work/WhatsAppStatusSaver/WhatsAppStatusSaver/local.properties | base64

      - name: Putting data into local.properties
        env:
          DATA: ${{ secrets.PROPERTIES_CONTENT }}
        run: echo $DATA > /home/runner/work/WhatsAppStatusSaver/WhatsAppStatusSaver/local.properties

      - name: Create Distribution.json
        run: cat /home/runner/work/WhatsAppStatusSaver/WhatsAppStatusSaver/distribution.json | base64

      - name: Putting data into distribution.json
        env:
          DATA: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT }}
        run: echo $DATA > /home/runner/work/WhatsAppStatusSaver/WhatsAppStatusSaver/distribution.json

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
             ${{ runner.os }}-gradle-    


      - name: Build App with Gradle and upload to Firebase app distribution
        run: ./gradlew assembleRelease appDistributionUploadRelease



